### ISSUE TITLE
Error: Command failed: lua ./tmp/dataraw.lua > ./tmp/dataraw.json

### ISSUE THREAD

**Issue by agalera** [WFCD/warframe-wikia-scrapers#53]
### Wikia Scrapers Issue

warframe-wikia-scrapers commit: 821dc411d2063a0fd201a619cccf7220a4501243
npm -v
6.5.0
nodejs -v
v11.9.0
lua -v      
Lua 5.0.3  Copyright (C) 1994-2006 Tecgraf, PUC-Rio
```
/mnt/src/dataScrapers/WikiaDataScraper.js:50
        throw (new Error(err));
        ^

Error: Error: Command failed: lua ./tmp/dataraw.lua > ./tmp/dataraw.json
lua: ./tmp/dataraw.lua:2: attempt to call a nil value
stack traceback:
	./tmp/dataraw.lua:2: in main chunk
	[C]: ?

    at cmd.get (/mnt/src/dataScrapers/WikiaDataScraper.js:50:16)
    at /mnt/node_modules/node-cmd/cmd.js:25:21
    at ChildProcess.exithandler (child_process.js:304:5)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Socket.emit (events.js:197:13)
    at Pipe._handle.close (net.js:611:12)
```
**Summary (short):**

---
**Description:**

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
You need to install Lua. Nothing is wrong with the project.
